services:
    reverse-proxy:
        image: traefik:v3.1
        command: --api.insecure=true --providers.docker
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    belle-epoque-frontend:
        build:
            context: ./
            target: client-dev
        develop:
            watch:
                - path: ./
                  target: /usr/local/app
                  action: sync
                  ignore:
                      - node_modules
                - path: package.json
                  target: /usr/local/app
                  action: rebuild
        labels:
            traefik.http.routers.belle-epoque-frontend.rule: Host(`localhost`)
            traefik.http.services.belle-epoque-frontend.loadbalancer.server.port: 3000
